name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: parsashafizade
          outputs: |
            Gaming/assets/snake/github-contribution-grid-snake.svg?palette=github-dark
            Gaming/assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update contribution snake"
          add: Gaming/assets/snake/
